# Generated by Django 4.2.8 on 2024-05-23 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('categoryName', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.TextField()),
                ('adult', models.BooleanField(default=False)),
                ('publisher', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('readers', models.ManyToManyField(blank=True, related_name='read_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster', models.TextField()),
                ('adult', models.BooleanField(default=False)),
                ('genre', models.TextField()),
                ('viewers', models.ManyToManyField(blank=True, related_name='watched_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('genre', models.TextField()),
                ('thumbnails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('score', models.PositiveIntegerField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='cultures.book')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_review', to='cultures.movie')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiced_at', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('choiced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ChoicedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiced_at', models.DateField(auto_now_add=True)),
                ('pages', models.IntegerField()),
                ('now_page', models.IntegerField()),
                ('time', models.TextField()),
                ('mood', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.book')),
                ('choiced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
